#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           clawOpen,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           clawMove,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[leftDrive] = vexRT[Ch3]; //Make left motor move
		motor[rightDrive] = vexRT[Ch2]; //Make right motor move

		if (vexRT[Btn5U] == 1){
			motor[clawOpen] = 127;//Claw open
		} else if(vexRT[Btn5D] == 1) {
			motor[clawOpen] = -127;
		}	else {
			motor[clawOpen] = 0;
		}

		if (vexRT[Btn6U] == 1){
			motor[clawMove] = 127;//Claw up
		}
		else{
			motor(clawMove) = 0 ;
		}

    if   (vexRT[Btn6D] == 1){
    	motor[clawMove] = -127;//Claw down
    }
    else{
    	motor(clawMove) = 0 ;
    }

	}
}
