#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           clawMove,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightHarvest,  tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           leftHarvest,   tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           plowMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int intakePower = 127;

task main()
{

	while(true)
	{

		motor[leftDrive] = vexRT[Ch3]; //Make left motor move
		motor[rightDrive] = vexRT[Ch2]; //Make right motor move
		motor[rightHarvest] = intakePower;
		motor[leftHarvest] = intakePower;
		wait1Msec(100);

		if (vexRT[Btn8D]== 1){
			motor[plowMotor] = 127;
	}
	  else if (vexRT[Btn8R] == 1 ){
	  	motor[plowMotor] = -127;
	}
	  else{
	  	motor[plowMotor] = 0 ;
	}


		if (vexRT[Btn5U] == 1){
			intakePower *= -1;
			writeDebugStreamLine("The intake power is: %d", intakePower);

		}

		if (vexRT[Btn6U] == 1){
			motor[clawMove] = 127;//Claw up
		}
		else if (vexRT[Btn6D] == 1){
    	motor[clawMove] = -127;//Claw down
    }
    else{
    	motor(clawMove) = 0 ;
    }

	}
}
